### ISSUE TITLE
Créer des comptes utilisateurs pour limiter l'accès

### ISSUE THREAD

**Issue by loicknuchel** [HumanTalks/humantalks-admin#1]

**Comment by sbouaked** [comment]
Possibilité de connecter ca à meetup ? et de synchro les droits ?

**Comment by loicknuchel** [comment]
Peut-être, mais pas sûr que ce soit vraiment intéressant comme on est pas beaucoup... Je pense plutôt faire une gestion de droits interne...
Si c'est vraiment utile on pourra toujours l'ajouter.
