### ISSUE TITLE
Amélioration soumission de talks

### ISSUE THREAD

**Issue by sbouaked** [HumanTalks/humantalks-admin#36]
Avoir un onglet dédiés aux talks soumis et une pastille indiquant le nombre de nouveaux talks soumis
Proposer des dates de disponibilité au moment de la soumission
recevoir un mail sur paris@humantalks.com pour chaque soumission (ou sur slack)

**Comment by loicknuchel** [comment]
+1 pour les propositions de disponibilités (ça simplifiera largement la gestion !)

Pour les notifs (mail ou slack), c'est prévu :)

Pour un onglet avec les talks soumis, je suis pas sûr que ce soit intéressant puisqu'ils sont affichés dans le détail du meetup... A voir.

**Comment by sbouaked** [comment]
oki super !  Pour les talks soumis, c'est juste pour savoir combien y'en a de nouveaux, et ne pas être obligé de créé un meetup pour faire le point.

**Comment by loicknuchel** [comment]
yep, d'ailleurs je me demandais pour les dates à venir, est-ce que je prends les dates des meetups qui sont à venir (du coup il faudrait les créer plusieurs mois à l'avance) ou est-ce que je calcule automatiquement les 2eme mardis pour les 6 prochains mois ? (mais du coup on ne pourra pas gérer d'exception ou autre, genre le mois d'août ou si on décale à cause d'un férié...)

PS: sinon c'est mieux de faire plusieurs issues pour des tâches différentes ^^

**Comment by sbouaked** [comment]
calcul automatiquement, te prends pas la tête, les exceptions sont rares

PS : oki pour les issues :p

**Comment by loicknuchel** [comment]
Bon ben c'est fait alors ;)
Faut juste que je le pousse en prod :)
