### ISSUE TITLE
pouvoir créer une proposition depuis l'admin

### ISSUE THREAD

**Issue by loicknuchel** [HumanTalks/humantalks-admin#54]
(n'envoi pas de mail de confirmation aux speakers)

**Comment by mparisot** [comment]
Il faudrait juste une checkbox ou un select sur "add a talk" pour changer le status, non?

**Comment by loicknuchel** [comment]
à réfléchir... peut être que les propositions sont redondantes avec les talks... (et du coup il faudrait simplement les supprimer et modifier un peu les talks)
