### ISSUE TITLE
Gestion des sponsors

### ISSUE THREAD

**Issue by mparisot** [HumanTalks/humantalks-admin#59]
Il nous faudrait une gestion des contacts sponsors : 

Nom de l'entreprise
Logo de l'entreprise
Nom du contact
telephone du contact
mail du contact
apero / annuel (certain pouvant etre les deux)
Pour les annuels la date de renouvellement du contrat (et recevoir un mail d'alerte 1 mois avant?)

Pouvoir associer un sponsors apero a un event

**Comment by loicknuchel** [comment]
Yep, à voir si on renomme pas les lieux en company qui peuvent avoir un lieu et/ou être sponsor...
Pareil, à discuter de la manière de gérer...
