### ISSUE TITLE
Pouvoir trier les talks par date DESC et filtrer par status

### ISSUE THREAD

**Issue by mparisot** [HumanTalks/humantalks-admin#60]
Pour voir les derniers sujets et ceux en attente c'est pas pratique actuellement

Je pense qu'il nous faut juste un tri par date et un filtre par status (proposé, en attente de planification, validé)

Pour le reste il suffit d'aller sur le site avec la recherche algolia

**Comment by loicknuchel** [comment]
Pour les talks en attente, tu les as sur la page détail d'un meetup à venir (normalement tu ne vas pas les chercher dans la liste des talks, après je suis d'accord avec toi)
