### ISSUE TITLE
Impossible d'ajouter une adresse en ajoutant un lieu

### ISSUE THREAD

**Issue by pixelastic** [HumanTalks/humantalks-admin#63]
![2016-11-30_15h36m50](https://cloud.githubusercontent.com/assets/283419/20789325/323f8ba4-b7b4-11e6-9041-84b2a052e590.gif)

La page se recharge dès que je sélectionne l'adresse dans le dropdown. La map GMaps s'affiche un instant, puis reload.

Chrome Version 54.0.2840.100 (64-bit)

**Comment by loicknuchel** [comment]
Hello,
J'ai pas de soucis sur mon chrome... 

Tu peux regarder si t'as une erreur dans la console ?
Tu peux regarder les données envoyées dans le formulaire ? (genre, est-ce qu'il y a tous les champs de l'adresse ou pas)

J'ai l'impression que quand tu sélectionnes une adresse, ça valide le formulaire (comme si tu faisais enter sur le champ input...)
Le code qui gère la sélection de lieu est là : https://github.com/HumanTalks/humantalks-admin/blob/master/app/assets/scripts/main.ts#L436

**Comment by pixelastic** [comment]
Ouais, on dirait que c'est ça. Quand je selectionne l'adresse, ça semble soumettre le form. Si je remplis pas le nom par exemple avant de choisir l'adresse, alors ça me marque que le form est invalide et ça le soumets pas.

Voici un bout de ma console en essayant d'ajouter l'adresse:

![image](https://cloud.githubusercontent.com/assets/283419/20927339/69f05a22-bbc1-11e6-9644-03e8b13bd10c.png)

**Comment by loicknuchel** [comment]
j'ai l'impression que ton browser (adblock?) bloque les scripts GMaps....
Tu peux tester sans adblock ?
Et test en HTTPS : https://humantalksparis.herokuapp.com/venues/create

**Comment by pixelastic** [comment]
Je viens de retester en https et en virant µBlock et toujours le même soucis.

**Comment by loicknuchel** [comment]
Ok, j'ai capté...
En fait le bug est présent quand tu fait "Enter" sur l'item (à fixer).
Pour l'instant, il suffit de cliquer sur la bonne adresse avec la souris (en mode workaround temporaire)
