### ISSUE TITLE
Impossible de selectionner un contact en ajoutant un lieu

### ISSUE THREAD

**Issue by pixelastic** [HumanTalks/humantalks-admin#64]
En essayant d'ajouter un nouveau lieu, la partie "Contact" est un select non-editable.

![image](https://cloud.githubusercontent.com/assets/283419/20926425/80b1d54c-bbbc-11e6-9af3-8d1ca259783d.png)

La console Chrome affiche cette url en erreur:
http://humantalksparis.herokuapp.com/api/select2/persons

```json

{
  "error" : {
    "code" : "Unknown",
    "message" : "Unexpected exception: java.lang.RuntimeException",
    "description" : "(/auth/role,List(ValidationError(List(Enumeration expected of type: 'class com.humantalks.internal.persons.Person$Role$', but it does not appear to contain the value: 'default'),WrappedArray())))"
  },
  "metas" : {
    "exec" : 78
  }
}
}```

Je vais rajouter les infos de contact en dur dans la partie commentaire pour l'instant

**Comment by loicknuchel** [comment]
fixé :)
Le pb était que je mettais un mauvais role à l'enregistrement d'un nouvel utilisateur et Camille est tombé dedans du coup la récupération des utilisateurs plante...
Bref, j'ai fixé en base, dans le code et le déploiement en prod est fait ;)
