### ISSUE TITLE
Rajouter l'organisateur en relation avec le contact de la salle

### ISSUE THREAD

**Issue by sbouaked** [HumanTalks/humantalks-admin#7]

**Comment by loicknuchel** [comment]
Dans les données d'une salle ? Pas sûr que ce soit pertinent... ça peut changer et il peut y avoir plusieurs personnes...
Pour moi le mieux c'est de le mettre dans le commentaire si besoin... non ?

**Comment by sbouaked** [comment]
Je voyais bien un truc à la trello (pour pouvoir s'attacher ou detacher sur une salle. Mais oki pour la description, mais dans la zone de note reservée aux orgas

**Comment by loicknuchel** [comment]
pour l'instant je pense tout mettre en privé et seulement ouvrir quelques endpoints utiles publiquement si besoin.
