### ISSUE TITLE
Doubler le titre et le nom du speaker avec un lien vers Twitter

### ISSUE THREAD

**Issue by antoinepeze** [HumanTalks/humantalks-admin#78]
Ma première issue sur GitHub !!

Vu qu'une image vaut 1000 mots...

![desktop](https://cloud.githubusercontent.com/assets/17899926/22546895/45e14e24-e93f-11e6-82be-0cefbefdfe4d.png)

**Comment by loicknuchel** [comment]
Description du meetup déjà générée
